server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /api
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: false
    max-age: 3600

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/sweetshop
  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890
      expiration: 86400000 # 24 hours

logging:
  level:
    com.sweetshop: DEBUG
